version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
          - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-node-{{ arch }}-{{ .Branch }}-
          - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: /tmp/workspace/build
          paths:
            - dist/*

      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Tests
          command: npm test

      - run:
          name: Tests coverage
          command: npm run test:coverage

  deploy-gh-pages:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - attach_workspace:
        at: /tmp/workspace/build

      - run:
          name: Deploy Github Pages
          command: ./scripts/deploy-ghpages.sh dist


workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - test
      - deploy-gh-pages:
          requires:
            - test
            - build
          # filters:
          #   branches:
          #     only: master
