version: 2
jobs:
  build:


    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
          - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-node-{{ arch }}-{{ .Branch }}-
          - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Tests coverage
          command: npm run test:coverage
