version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
          - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-node-{{ arch }}-{{ .Branch }}-
          - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: dist
          paths:
            - ./*

      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Tests
          command: npm test

      - run:
          name: Tests coverage
          command: npm run test:coverage

  deploy-gh-pages:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - attach_workspace:
          at: dist

      - add_ssh_keys:
          fingerprints:
            - "33:2f:10:7f:27:39:93:a0:2d:99:d8:c8:81:30:29:82"

      - run:
          name: Deploy Github Pages
          command: ./scripts/deploy-ghpages.sh dist

  doc-page:
    docker:
      - image: circleci/node:8

    working_directory: ~/lights-react-out

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "59:74:63:95:5f:c5:ce:84:e9:56:85:2b:d4:cd:6f:c3"

      - run:
          name: Install Dev Packages
          command: npm install --only=dev

      - run:
          name: Generate doc
          command: npm run doc

      - run:
          name: Deploy Doc to Github Pages
          command: ./scripts/deploy-ghpages.sh doc https://github.com/AnguloHerrera/lights-react-out-doc.git master


workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - test
      - deploy-gh-pages:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
      - doc-page
          # filters:
          #   branches:
          #     only: master
